version: "3"
services:
  webapp:
    build:
      dockerfile: ./ci/Dockerfile
      context: ../
    container_name: web-app
    restart: always
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    tty: true
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      NUXT_PUBLIC_API_BASE: "http://localhost:3001/api/"