version: "3"
services:
 web-app:
  build:
   dockerfile: ./ci/docker/production/Dockerfile
   context: ../
  image: aide-financiere-webapp:latest
  container_name: web-app
  command: [sh, -c, "npm run start"]
  restart: always
  working_dir: /usr/src/app
  ports:
   - "3000:3000"
  tty: true
  environment:
   HOST: 0.0.0.0
   PORT: 3000
   NUXT_PUBLIC_API_BASE: "http://localhost:6001/api/"
